---
title: "Multi-State Model Analysis: Covariates"
date: today
format:
  html:
    df-print: paged
    toc: true
    toc-float: true
    toc-depth: 3
    code-fold: true
    theme: default
    embed-resources: true
editor: source
editor_options: 
  markdown: 
    wrap: 72
execute:
  cache: false
---

```{r}
#| label: setup
#| include: false

rm(list = ls())

library(here)
library(tidyverse)
library(knitr)
library(kableExtra)
library(tableone)
library(Hmisc)
library(ggpubr)
library(viridis)
library(gridExtra)
library(grid)

```

```{r}
#| label: load-data
#| include: false

source(here("R", "00-config.R"))
source(here("R", "00f-fns-tbl_figs.R"))
source(here("R", "00d-fns-model_eval.R"))

pt_stg <- readRDS(here("data", "pt_stg.rds"))
crude_rates <- readRDS(here("data", "crude_rates.rds"))

time_comp <- readRDS(here("data", "time_inhomog_comp.rds"))
time_inhomog_models <- readRDS(here("data", "time_inhomog_models.rds"))
```

## Timeline

```{r}
#| label: timeline-data
#| echo: true

state_order <- factor(c("M", "S", "D", "R"), ordered = TRUE)

timeline_hosp_data <- pt_stg %>%
  dplyr::select(model, deid_enc_id, DaysSinceEntry, DaysSincePos, stage, state) %>%
  filter(model == "base_model") %>%
  mutate(state_type = ifelse(grepl("M", state), "Moderate", "Severe")) %>%
  group_by(deid_enc_id) %>%
  mutate(LOS = n(),
         n_severe = sum(ifelse(state_type == "Severe", 1, 0))) %>%
  ungroup() %>%
  arrange(desc(LOS), desc(n_severe)) %>%
  mutate(deid_enc_id = factor(deid_enc_id, levels = unique(deid_enc_id))) %>%
  mutate(state = factor(state, levels = levels(state_order)))

timeline_cal_data <- pt_stg %>%
  dplyr::select(model, deid_enc_id, date, CalendarTime, stage, state) %>%
  filter(model == "base_model") %>%
  mutate(state_type = ifelse(grepl("M", state), "Moderate", "Severe")) %>%
  arrange(date) %>%
  mutate(deid_enc_id = factor(deid_enc_id, levels = unique(deid_enc_id))) %>%
  mutate(state = factor(state, levels = levels(state_order)))

```

## Supp fig 1: Timelines

```{r}

timeline_pA <- ggplot(data = timeline_hosp_data,
       aes(x = DaysSinceEntry, y = deid_enc_id, color = state, fill = state)) +
  geom_tile(aes(width = 1, height = 0.8)) +
  theme_minimal(base_size = 10) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid = element_blank(),
        legend.position = "bottom") +
  scale_color_viridis_d(breaks = state_order) +
  scale_fill_viridis_d(breaks = state_order) +
  scale_x_continuous(name = "Days since hospital admission", 
                     breaks = seq(0, 60, by = 5),
                     limits = c(0, 30))

# timeline_pA

# order_temp <- timeline_hosp_data %>%
#   group_by(deid_enc_id) %>%
#   summarise(min_day = min(DaysSincePos)) %>%
#   arrange(min_day) %>%
#   mutate(deid_enc_id = factor(deid_enc_id, levels = unique(deid_enc_id)))
# 
# timeline_hosp_data <- timeline_hosp_data %>%
#   mutate(deid_enc_id = factor(deid_enc_id, levels = levels(order_temp$deid_enc_id)))

timeline_pB <- ggplot(data = timeline_hosp_data,
       aes(x = DaysSincePos, y = deid_enc_id, color = state, fill = state)) +
  geom_tile(aes(width = 1, height = 0.8)) +
  theme_minimal(base_size = 10) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid = element_blank(),
        legend.position = "bottom") +
  scale_color_viridis_d(breaks = state_order) +
  scale_fill_viridis_d(breaks = state_order) +
  scale_x_continuous(name = "Days since positive COVID test", 
                     breaks = seq(-10, 60, by = 5),
                     limits = c(NA, 30))

# timeline_pB

timeline_pC <- ggplot(data = timeline_cal_data,
       aes(x = date, y = deid_enc_id, color = state, fill = state)) +
  geom_tile(aes(width = 1, height = 1.5)) +
  theme_minimal(base_size = 10) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        panel.grid = element_blank(),
        legend.position = "bottom") +
  scale_color_viridis_d(breaks = state_order) +
  scale_fill_viridis_d(breaks = state_order) +
  scale_x_date(date_labels = "%b %Y", date_breaks = "3 months")

# timeline_pC

timeline_plot <- (timeline_pA + timeline_pB) / timeline_pC + 
  plot_annotation(tag_levels = 'A') + 
  plot_layout(guides = 'collect', heights = c(1, 1)) & 
  theme(legend.position = 'bottom')

ggsave(
  timeline_plot,
  filename = here("figs", "suppfig_timelines.png"),
  width = 8,
  height = 7,
  dpi = 300
)

```

```{r}
#| label: time-hrs-prep

days_hrs_sp <- extract_spline_hazard_ratios(
  fitted_msm_models = time_inhomog_models,
  spline_var = "DaysSinceEntry",
  reference_value = 1  # or NULL for mean
)

cal_hrs_sp <- extract_spline_hazard_ratios(
  fitted_msm_models = time_inhomog_models,
  spline_var = "CalendarTime",
  reference_value = 1  # or NULL for mean
)

time_hrs_sp <- rbind(
  days_hrs_sp,
  cal_hrs_sp
) %>%
  rename(variable = spline_variable) %>%
  mutate(type = "spline")

days_hrs_lin <- extract_linear_hazard_ratios(
  fitted_msm_models = time_inhomog_models,
  linear_var = "DaysSinceEntry",
  reference_value = 1  # or NULL for mean
)

cal_hrs_lin <- extract_linear_hazard_ratios(
  fitted_msm_models = time_inhomog_models,
  linear_var = "CalendarTime",
  reference_value = 1  # or NULL for mean
)

time_hrs_lin <- rbind(
  days_hrs_lin,
  cal_hrs_lin
) %>%
  rename(variable = linear_variable) %>%
  mutate(type = "linear")

time_hrs <- rbind(
  time_hrs_sp,
  time_hrs_lin
)

```

```{r}
#| label: time-hrs-plot

time_hrs_plot <- ggplot(data = time_hrs, aes(x = covariate_value, y = hr, color = type, fill = type)) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  geom_ribbon(aes(ymin = pmax(hr_lower, 0.1), 
                  ymax = pmin(hr_upper, 160)), 
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1)  +
  facet_grid(transition ~ variable, scales = "free",
             labeller = labeller(
               variable = c(
               "DaysSinceEntry" = "Hospital Time",
               "CalendarTime" = "Calendar Time"
             ))) +
  scale_y_log10(limits = c(0.1, 160)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 4)) +
  labs(
    x = "Time (days)",
    y = "Hazard Ratio (log scale)",
    color = "Model",
    fill = "Model"
  ) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom") +
  scale_color_manual(values = c("linear" = "#C77966", "spline" = "#2F343B"),
                     labels = c("Linear", "Spline"),
                     name = "Model type") +
  scale_fill_manual(values = c("linear" = "#C77966", "spline" = "#2F343B"),
                    labels = c("Linear", "Spline"),
                    name = "Model type") +
  guides(color = "none", fill = guide_legend(override.aes = list(alpha = 1, shape = 15)))

time_hrs_plot

ggsave(time_hrs_plot,
       filename = here("figs", "fig_time_inhomog_hr.png"),
       width = 6,
       height = 8,
       dpi = 300)

```


```{r}
#| label: load-cv-data

rds_files <- list.files(
    path = here("data", "cv_results", "time_inhomog"),
    pattern = "\\.rds$",
    ignore.case = TRUE,
    full.names = TRUE
)
  
# Read all files into a list
rds_data <- lapply(rds_files, readRDS)
  
# Extract file names (without path and extension) for naming
file_names <- tools::file_path_sans_ext(basename(rds_files))
names(rds_data) <- file_names

elements_to_remove <- c("cv_metadata", "cv_summary_all_models")
rds_data <- rds_data[!names(rds_data) %in% elements_to_remove]

```

```{r}
#| label: prep-cv-data

base_cv <- readRDS(here("data", "cv_results", "base", "cv_base_model_X..1.rds")) %>%
  .$fold_metrics %>%
  mutate(model = "No covariates")

tibble_name <- "fold_metrics"  
column_name <- "model"     

combined_data <- map2_dfr(
  rds_data, 
  names(rds_data),
  ~ {
    if (tibble_name %in% names(.x)) {
      .x[[tibble_name]] %>%
        mutate(!!column_name := .y)
    } else {
      NULL 
    }
  }
)

combined_data <- combined_data %>%
  bind_rows(base_cv) %>%
  mutate(model_structure = sub("^[^_]*_(.*)_[^_]*$", "\\1", model),
         covariates = sub("^.*?\\.\\.(.*)$", "\\1", model)) %>%
  mutate(covariate = case_when(
    grepl("DaysSinceEntry", covariates) & grepl("ns", covariates) ~ "Days Since Entry (spline)",
    grepl("DaysSinceEntry", covariates) ~ "Days Since Entry (linear)",
    grepl("CalendarTime", covariates) & grepl("ns", covariates) ~ "Calendar Time (spline)",
    grepl("CalendarTime", covariates) ~ "Calendar Time (linear)",
    covariates == "No covariates" ~ "No covariates",
    TRUE ~ NA
  )) %>%
  dplyr::select(-c(model_structure, model, covariates))

pred_err_dat <- combined_data %>%
  dplyr::select(covariate, ends_with("_mae"), ends_with("_auc"), starts_with("brier_"), starts_with("calibration")) %>%
  pivot_longer(cols = -covariate, 
               names_to = "metric", values_to = "value")

pred_err_summ <- pred_err_dat %>%
  group_by(covariate, metric) %>%
  summarise(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE),
    median = median(value, na.rm = TRUE),
    IQR = IQR(value, na.rm = TRUE),
    n = n(),
    .groups = 'drop'
  ) %>%
  mutate(
    model_name = case_when(
      covariate == "No covariates" ~ "No covariates",
      covariate == "Days Since Entry (linear)" ~ "Hospital time\n(linear)",
      covariate == "Days Since Entry (spline)" ~ "Hospital time\n(spline)",
      covariate == "Calendar Time (linear)" ~ "Calendar time\n(linear)",
      covariate == "Calendar Time (spline)" ~ "Calendar time\n(spline)",
      TRUE ~ NA_character_
    )
  )

```

```{r}
#| label: cv-results-table

pred_err_summ %>%
  mutate(text = paste0(
    round(mean, 3), " (", 
    round(sd, 3), ")"
  )) %>%
  dplyr::select(covariate, metric, text) %>%
  pivot_wider(names_from = metric, values_from = text) %>%
  dplyr::select(covariate, 
                brier_death, brier_severe,
                calibration_slope_death, calibration_slope_severe,
                total_los_mae, days_severe_mae,
                death_auc, severe_auc) %>%
  kable(format = "html",
        caption = "Cross-Validation Results by Covariate Specification of time",
        col.names = c("Model", "Brier Score (Death)", "Brier Score (Severe)",
                      "Calibration Slope (Death)", "Calibration Slope (Severe)",
                      "MAE (Total LOS)", "MAE (Days Severe)", "AUC (Death)", "AUC (Severe)"
                      )) %>%
  kable_styling(full_width = FALSE, position = "center")

```

```{r}
#| label: prep-cv-plot

metric_order <- c("brier_death", "brier_severe", 
                  "death_auc", "severe_auc", 
                  "calibration_slope_death", "calibration_slope_severe", 
                  "total_los_mae", "days_severe_mae")

metric_labels <- c("brier_death" = "Brier Score: Death",
                   "brier_severe" = "Brier Score: Severe",
                   "death_auc" = "AUROC: Death",
                   "severe_auc" = "AUROC: Severe",
                   "calibration_slope_death" = "Calibration Slope: Death",
                   "calibration_slope_severe" = "Calibration Slope: Severe",
                   "total_los_mae" = "MAE: Total LOS",
                   "days_severe_mae" = "MAE: Days Severe")

pred_err_summ$metric <- factor(pred_err_summ$metric, levels = metric_order)

facet_limits <- data.frame(
  metric = factor(metric_order,
                  levels = metric_order),
  # ymin = rep(NA, length(metric_order)),
  # ymax = rep(NA, length(metric_order))
  ymin = c(0.07, 0.18, 0.5, 0.5, NA, NA, 7, 7),
  ymax = c(0.09, 0.28, 1, 1, NA, NA, 19, 19)
)

```


```{r}
#| label: cv-results-plot

time_cv_plot <- ggplot(data = subset(pred_err_summ, covariate != "No covariates")) +
  geom_blank(data = facet_limits, aes(x = 1, y = ymin)) +
  geom_blank(data = facet_limits, aes(x = 1, y = ymax)) +
  geom_rect(data = subset(pred_err_summ, covariate == "No covariates"),
            aes(ymin = mean - sd, ymax = mean + sd),
            xmin = -Inf, xmax = Inf,
            alpha = 0.6, fill = "grey80") +
  geom_point(aes(y = mean, x = model_name, color = model_name), size = 2.5) +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd, x = model_name, color = model_name), width = 0.2) +
  geom_hline(data = subset(pred_err_summ, covariate == "No covariates"), 
             aes(yintercept = mean), linetype = "dashed") +
  facet_wrap(~ metric, scales = "free_y", ncol = 2,
             labeller = labeller(metric = metric_labels)) +
  scale_x_discrete() +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 3)) +
  scale_color_manual(breaks = c("Hospital time\n(linear)", "Hospital time\n(spline)", 
                                "Calendar time\n(linear)", "Calendar time\n(spline)"),
                     values = c("#C77966", "#2F343B", "#C77966", "#2F343B")) +
  theme_minimal(base_size = 12) +
  theme(axis.title = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(size = 6)) +
  guides(color = "none")

time_cv_plot

```

```{r}
#| label: combine-cv-plot

design1 <- "
12
33
"
panelA <- timeline_pA + timeline_pB + timeline_pC +
  plot_annotation(tag_levels = "i") +
  plot_layout(design = design1, guides = "collect") & 
  theme(legend.position = 'bottom')

panelA <- wrap_elements(full = panelA)

panelC <- (time_hrs_plot / guide_area()) +
  plot_layout(heights = c(1, 0.1), guides = "collect") &
  theme(legend.position = "bottom")

panelC <- wrap_elements(full = panelC)

# Final figure: A (panelA), B (hrs), C (cv)
design_final <- "
13
23
"

time_comb_plot <- panelA + time_cv_plot + panelC +
  plot_layout(design = design_final, 
              heights = c(2, 3),
              widths = c(1.5, 1)) +
  plot_annotation(tag_levels = "A") &
  theme(plot.tag.position = c(0.01, 0.99), # x, y in npc coords
    plot.tag = element_text(margin = margin(r = 6, b = 6)))

time_comb_plot

ggsave(
  time_comb_plot,
  filename = here("figs", "fig_time_inhomog_hr_cv.png"),
  width = 9,
  height = 8,
  dpi = 300
)

```

```{r}
#| label: slide-deck-plot

timeline_pA_slides <- ggplot(data = timeline_hosp_data,
       aes(x = DaysSinceEntry, y = deid_enc_id, color = state, fill = state)) +
  geom_tile(aes(width = 1, height = 0.8)) +
  theme_minimal(base_size = 10) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid = element_blank(),
        legend.position = "bottom") +
  scale_color_viridis_d() +
  scale_fill_viridis_d() +
  scale_x_continuous(name = "Days since hospital admission", 
                     breaks = seq(0, 60, by = 5),
                     limits = c(0, 30))

timeline_pA_slides

timeline_pC_slides <- ggplot(data = timeline_cal_data,
       aes(x = date, y = deid_enc_id, color = state, fill = state)) +
  geom_tile(aes(width = 1, height = 1.5)) +
  theme_minimal(base_size = 10) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        panel.grid = element_blank(),
        legend.position = "bottom") +
  scale_color_viridis_d() +
  scale_fill_viridis_d() +
  scale_x_date(date_labels = "%b\n%Y", date_breaks = "3 months")

timeline_pC_slides

hosp_time_hrs_plot <- ggplot(data = subset(time_hrs, variable == "DaysSinceEntry" & transition %in% c("S -> M", "M -> D")), 
                        aes(x = covariate_value, y = hr, color = type, fill = type)) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  geom_ribbon(aes(ymin = pmax(hr_lower, 0.5), 
                  ymax = pmin(hr_upper, 20)), 
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1)  +
  facet_wrap(~transition, nrow = 2) +
  scale_y_log10(limits = c(0.5, 20)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 4), limits = c(0, 30)) +
  labs(
    x = "Time",
    y = "Hazard Ratio (log scale)",
    color = "Model",
    fill = "Model"
  ) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom") +
  scale_color_manual(values = c("linear" = "#C77966", "spline" = "#2F343B"),
                     labels = c("Linear", "Spline"),
                     name = "Model type") +
  scale_fill_manual(values = c("linear" = "#C77966", "spline" = "#2F343B"),
                    labels = c("Linear", "Spline"),
                    name = "Model type") +
  guides(color = "none", fill = guide_legend(override.aes = list(alpha = 1, shape = 15)))

cal_time_hrs_plot <- ggplot(data = subset(time_hrs, variable == "CalendarTime" & transition %in% c("S -> M", "M -> D")), 
                        aes(x = covariate_value, y = hr, color = type, fill = type)) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  geom_ribbon(aes(ymin = pmax(hr_lower, 0.5), 
                  ymax = pmin(hr_upper, 20)), 
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1)  +
  facet_wrap(~transition, nrow = 2) +
  scale_y_log10(limits = c(0.5, 20)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 4)) +
  labs(
    x = "Time",
    y = "Hazard Ratio (log scale)",
    color = "Model",
    fill = "Model"
  ) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom") +
  scale_color_manual(values = c("linear" = "#C77966", "spline" = "#2F343B"),
                     labels = c("Linear", "Spline"),
                     name = "Model type") +
  scale_fill_manual(values = c("linear" = "#C77966", "spline" = "#2F343B"),
                    labels = c("Linear", "Spline"),
                    name = "Model type") +
  guides(color = "none", fill = guide_legend(override.aes = list(alpha = 1, shape = 15)))

cal_time_hrs_plot

timeline_pA_slides + timeline_pC_slides + 
  hosp_time_hrs_plot + cal_time_hrs_plot +
  plot_layout(guides = 'collect',
              axes = 'collect') & 
  theme(legend.position = 'bottom')

ggsave(
  filename = here("figs", "fig_time_inhomog_hr_slides.png"),
  width = 7,
  height = 5,
  dpi = 300
)

timeline_pA_slides + 
  hosp_time_hrs_plot +
  timeline_pC_slides +
  cal_time_hrs_plot +
  plot_layout(guides = 'collect',
              axes = 'collect',
              nrow = 4) & 
  theme(legend.position = 'bottom')

ggsave(
  filename = here("figs", "fig_time_inhomog_hr_slides.png"),
  width = 6,
  height = 8,
  dpi = 300
)

```

