---
title: "Model Outputs: Transition Analysis"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
---

```{r setup, include=FALSE}
library(msm)
library(tidyverse)
library(knitr)
library(kableExtra)
library(here)
```

## Load Saved Model Outputs

```{r load-model-results}
# Load all relevant model outputs saved from 02a-base-models.Rmd
fitted_models <- readRDS(here("data", "temp", "base_models.rds"))
tidied_base_results <- readRDS(here("data", "temp", "base_mod_rates_tidy.rds"))
tidied_base_pmats <- readRDS(here("data", "temp", "base_mod_pmats_tidy.rds"))
cross_tab_draic_tidy <- readRDS(here("data", "temp", "base_mod_draic.rds"))
```

## Model Summary Table

```{r model-summary-table}
model_stats <- map_dfr(names(fitted_models), function(name) {
  mod <- fitted_models[[name]]
  data.frame(
    Model = name,
    LogLik = logLik(mod),
    AIC = AIC(mod),
    BIC = BIC(mod)
  )
})

# Save base model stats for later comparison
base_model_aic <- model_stats$AIC[1]
model_stats <- model_stats %>%
  mutate(DRAIC = AIC - base_model_aic)

kable(model_stats, caption = "Model Summary Table") %>%
  kable_styling(full_width = F)
```

## Transition Rate Tables (Q-matrix)

```{r qmatrix-table}
qmat_list <- readRDS(here("data", "temp", "mod_qmat_list.rds"))

qmat_tables <- map2(qmat_list, names(qmat_list), function(mat, name) {
  kable(as.data.frame(round(mat, 4)), caption = paste("Transition Q-Matrix for", name)) %>%
    kable_styling(full_width = F)
})

qmat_tables
```

## Transition Probabilities

```{r transition-probs}
pmats_df <- readRDS(here("data", "temp", "mod_pmats_tidy.rds"))

pmats_df %>%
  select(model, from, to, estimate, LL, UL) %>%
  dplyr::filter(!from %in% c("D", "R")) %>%
  kable(caption = "Estimated 1‑day transition probabilities (rows = current state, columns = next state)") %>%
  kable_styling(full_width = FALSE, bootstrap_options = c("striped", "hover")) %>%
  collapse_rows(columns = 1, valign = "top")
```

## Sojourn Times (Expected Time in State)

```{r sojourn-times}
sojourns_list <- readRDS(here("data", "temp", "base_mod_sojourns.rds"))

sojourns <- map2(sojourns_list, names(sojourns_list), function(st, name) {
  df <- data.frame(State = names(st$estimates), Time = round(st$estimates, 2))
  kable(df, caption = paste("Sojourn Times for", name)) %>%
    kable_styling(full_width = F)
})

sojourns
```

## Deviance Residuals by Transition (Optional Diagnostic)

```{r residuals-plot, fig.height=5, fig.width=7}
par(mfrow = c(1, length(fitted_models)))
for (name in names(fitted_models)) {
  mod <- fitted_models[[name]]
  dev_res <- residuals(mod, type = "deviance")
  plot(dev_res, main = paste("Deviance Residuals\n", name), ylab = "Residuals")
}
```

## Model Comparisons (ΔRAIC)

```{r model-comparison-tables-draic, echo=FALSE}
cross_tab_draic_tidy %>%
  mutate(across(where(is.numeric), round, 2)) %>%
  kableExtra::kable(caption = "Difference in RAIC between base models") %>%
  kableExtra::kable_styling(full_width = FALSE, bootstrap_options = c("striped", "hover"))
```
